networks:
  rerandom-net:
    driver: bridge
    attachable: true

volumes:
  rerandom-backend-data:
  postgres-data:

services:
  backend:
    container_name: rerandom-backend
    build:
      context: backend/
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/ping"]
      interval: 5s
      retries: 30
      timeout: 3s
      start_period: 2s
    restart: "no"
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - APP_HOST=:8000
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - POSTGRES_TIMEZONE=Europe/Moscow
      - PRODUCTION_ENV=true
      - RUNTIME_PRODUCTION=true
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rerandom-net

  postgres:
    image: postgres:17-alpine
    container_name: rerandom-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rerandom-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    command: ["postgres", "-c", "listen_addresses=*"]

  nginx:
    image: nginx:stable-alpine
    container_name: rerandom-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/docker_nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/server.crt:/etc/ssl/certs/server.crt:ro
      - ./ssl/server.key:/etc/ssl/private/server.key:ro
      - ./nginx:/var/www/html:ro
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - rerandom-net