name: Google sheet sync web build

on:
  push:
    branches: [main]
    paths:
      - 'gs_sync/**'
      - '.github/workflows/gs_sync_sync.yml'
  pull_request:
    branches: [main]
    paths:
      - 'gs_sync/**'
      - '.github/workflows/gs_sync_sync.yml'
  workflow_dispatch:

env:
  LONG_IMAGE_TAG: ${{ github.sha }}


jobs:
  build-backend:
    name: Build web syncer part
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Установка короткого хеша
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Логин в GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Приведение имени репозитория к нижнему регистру
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Сборка и пуш образа backend
        uses: docker/build-push-action@v5
        with:
          context: gs_sync
          file: gs_sync/Dockerfile.web
          tags: |
            ghcr.io/${{ env.REPO_NAME }}/gs_sync-web-backend:latest
            ghcr.io/${{ env.REPO_NAME }}/gs_sync-web-backend:${{ env.IMAGE_TAG }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max